version: ~> 1.0
matrix:
    include:
        - os: osx
          osx_image: xcode8.3
        - os: linux
          dist: trusty
          sudo: false
          language: python
          python: "3.6"
          addons:
              apt:
                  sources:
                      - sourceline: 'ppa:beineri/opt-qt594-trusty'
                  packages:
                      - libc++-dev
                      - libc++abi-dev
                      - libx11-xcb-dev
                      - libxcb-glx0-dev
                      - libxcb-icccm4-dev
                      - libxcb-image0-dev
                      - libxcb-keysyms1-dev
                      - libxcb-randr0-dev
                      - libxcb-render-util0-dev
                      - libxcb-shape0-dev
                      - libxcb-shm0-dev
                      - libxcb-sync0-dev
                      - libxcb-xfixes0-dev
                      - libxcb-xinerama0-dev
                      - libxcb1-dev
                      - libxrender-dev

before_install:
    - export PATH=$PATH:/Library/Frameworks/Python.framework/Versions/3.7/bin
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          curl -OL https://www.python.org/ftp/python/3.7.6/python-3.7.6-macosx10.9.pkg
          && sudo installer -pkg python-3.7.6-macosx10.9.pkg -target /
          && pip3 install conan
          && conan config install https://vuo.org/sites/default/files/conan-macos.zip
      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
             pip install conan
          && conan config install --source-folder vuo-conan https://vuo.org/sites/default/files/conan-linux.zip
      ; fi

install:
    - conan user

script:
    - while sleep 540; do echo "===== 9 minute mark ====="; done &
    - >
      set -o pipefail ; conan create . vuo/stable 2>&1 | egrep -v --line-buffered 'In file included from|warnings? generated|warning: comparison of constant|warning: unused parameter|has been explicitly marked deprecated|warning: .* is deprecated| *(~*)? ?\^ ?~*'
      && conan upload --remote vuo --all --no-overwrite all --confirm qt/*
    - kill %1
