matrix:
    include:
        - os: osx
          osx_image: xcode7.3
          language: cpp
          compiler: clang
        - os: linux
          dist: trusty
          sudo: false
          language: python
          python: "3.6"
          addons:
              apt:
                  sources:
                      - sourceline: 'ppa:beineri/opt-qt594-trusty'
                  packages:
                      - libc++-dev
                      - libc++abi-dev
                      - libx11-xcb-dev
                      - libxcb-glx0-dev
                      - libxcb-icccm4-dev
                      - libxcb-image0-dev
                      - libxcb-keysyms1-dev
                      - libxcb-randr0-dev
                      - libxcb-render-util0-dev
                      - libxcb-shape0-dev
                      - libxcb-shm0-dev
                      - libxcb-sync0-dev
                      - libxcb-xfixes0-dev
                      - libxcb-xinerama0-dev
                      - libxcb1-dev
                      - libxrender-dev

cache:
    directories:
        - /usr/local/Cellar/conan
        - /usr/local/Cellar/gdbm
        - /usr/local/Cellar/libffi
        - /usr/local/Cellar/openssl
        - /usr/local/Cellar/pkg-config
        - /usr/local/Cellar/python
        - /usr/local/Cellar/readline
        - /usr/local/Cellar/sqlite
        - /usr/local/Cellar/xz
        - /usr/local/opt/python
        - /usr/local/opt/qt

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
             ( brew link conan || ( brew update &> /dev/null && travis_wait brew install --force-bottle conan ) )
          && ( brew link xz    || ( brew update &> /dev/null && travis_wait brew install --force-bottle xz    ) )
          && conan config install --source-folder vuo-conan https://vuo.org/sites/default/files/conan-macos.zip
      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
             pip install conan
          && conan config install --source-folder vuo-conan https://vuo.org/sites/default/files/conan-linux.zip
      ; fi

install:
    - conan user

script:
    - true
