matrix:
    include:
        - os: osx
          osx_image: xcode7.3
          language: cpp
          compiler: clang
        - os: linux
          dist: trusty
          sudo: false
          language: python
          python: "3.6"
          addons:
              apt:
                  sources:
                      - sourceline: 'ppa:beineri/opt-qt594-trusty'
                  packages:
                      - libc++-dev
                      - libc++abi-dev
                      - libx11-xcb-dev
                      - libxcb-glx0-dev
                      - libxcb-icccm4-dev
                      - libxcb-image0-dev
                      - libxcb-keysyms1-dev
                      - libxcb-randr0-dev
                      - libxcb-render-util0-dev
                      - libxcb-shape0-dev
                      - libxcb-shm0-dev
                      - libxcb-sync0-dev
                      - libxcb-xfixes0-dev
                      - libxcb-xinerama0-dev
                      - libxcb1-dev
                      - libxrender-dev
                      - qt59qbs

cache:
    directories:
        - /usr/local/Cellar/conan
        - /usr/local/Cellar/gdbm
        - /usr/local/Cellar/libffi
        - /usr/local/Cellar/openssl
        - /usr/local/Cellar/pkg-config
        - /usr/local/Cellar/python
        - /usr/local/Cellar/qbs
        - /usr/local/Cellar/qt
        - /usr/local/Cellar/readline
        - /usr/local/Cellar/sqlite
        - /usr/local/Cellar/xz
        - /usr/local/opt/python
        - /usr/local/opt/qt

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
             ( brew link conan || ( brew update &> /dev/null && travis_wait brew install --force-bottle conan ) )
          && ( brew link qbs   || ( brew update &> /dev/null && travis_wait brew install --force-bottle qbs   ) )
          && ( brew link xz    || ( brew update &> /dev/null && travis_wait brew install --force-bottle xz    ) )
          && conan config install https://vuo.org/sites/default/files/conan-macos.zip
      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
             pip install conan
          && conan config install https://vuo.org/sites/default/files/conan-linux.zip
          && . /opt/qt59/bin/qt59-env.sh
      ; fi

install:
    - qbs --version
    - qbs setup-qt --detect
    - qbs setup-toolchains --detect
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
             qbs config defaultProfile clang
      ; fi
    - conan user

script:
    - while sleep 540; do echo "===== 9 minute mark ====="; done &
    - >
      set -o pipefail ; conan create . vuo/stable 2>&1 | egrep -v --line-buffered 'In file included from|warnings? generated|warning: comparison of constant|warning: unused parameter|has been explicitly marked deprecated|warning: .* is deprecated| *(~*)? ?\^ ?~*'
      && conan upload --remote vuo --all --confirm qt/*
    - kill %1
